### ISSUE TITLE
Dockerize dns app

### ISSUE THREAD

**Issue by serain** [mwrlabs/dref#38]
The `dns` app can be dockerized.

The image should be pushed to Dockerhub on tag builds.

At the moment we'll keep the configuration loading as is (YAML) but in the future we should load required params (address and domain) from env vars.

**Comment by 0ca** [comment]
Hi, 

This is not totally related with this issue, but maybe it's useful for the DNS server code.

I found this project that is pretty similar, a DNS server for DNS rebinding attacks.
https://github.com/brannondorsey/whonow/blob/master/index.js

Maybe you are interested in using some of that code instead of creating manually the DNS responses.
